<?php
/**
 * NeoTheme Austrlia (Neo Industries Pty Ltd)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Neo Industries Pty LTD Non-Distributable Software Modification License (NDSML)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.neotheme.com.au/legal/licenses/NDSM.html
 * If the license is not included with the package or for any other reason, 
 * you did not receive your licence please send an email to 
 * license@neotheme.com.au so we can send you a copy immediately.
 *
 * This software comes with no warrenty of any kind. By Using this software, the user agrees to hold 
 * Neo Industries Pty Ltd harmless of any damage it may cause.
 *
 * @category    modules
 * @module      NeoTheme_ImageRotator
 * @copyright   Copyright (c) 2011 Neo Industries Pty Ltd (http://www.neotheme.com.au)
 * @license     http://www.neotheme.com.au/  Non-Distributable Software Modification License(NDSML 1.0)
 */
/**
 * @see NeoTheme_Blog_Block_Post
 */


 $_helper = $this->helper('catalog/output');
 $formatType = Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_FORMAT_TYPE);
 $format = ($formatType != 'custom')?
    Mage::app()->getLocale()->getDateTimeFormat($formatType): 
    Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_CUSTOM_FORMAT);
?>
<div class="blog blog-detail">
    <article class="post">
    	<div class="page-title post-title"><h1><?php echo $this->getPost()->getTitle(); ?></h1></div>
        <div class="post-metadata">
            <div class="post-time">
                <?php echo $this->__('Posted On: ');?> 
                <?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>
                <?php  echo  Mage::app()->getLocale()->date($date)->toString($format); ?>
            </div>
            <?php if ($this->getPost()->getAuthor()): ?>
            <div class="post-author"><?php echo $this->__('by'); ?> <?php echo $this->getPost()->getAuthor(); ?></div>
            <?php endif;?>
        </div>

        <div class="post-content">
            <?php echo $this->getPost()->getContentHtml();?>
        </div>
        
        <div class="post-info">
            <?php if ( (int) $this->getPost()->getStatus() == NeoTheme_Blog_Model_Post::STATUS_DRAFT) : ?>
                <h3 style="color:red;"><?php echo $this->__('[Draft] (not visible publicly)');?></h3>
            <?php endif; ?>

            <?php if (Mage::helper('neotheme_blog')->isCategoryShownInFrontend()): ?>
                <?php if ( $this->getPost()->getCategories()->count()) : ?>
                <ul class="post-categories">
                    <?php echo $this->__('Posted In: ');?>
                    <?php $i = 0; ?>
                    <?php foreach($this->getPost()->getCategories() as $category):?>
                        <?php $catName =  ($i > 0)? ',' . $category->getName() : $category->getName(); ?>
                            <li><a href="<?php echo $category->getListUrl();?>"><?php echo $catName; ?></a></li>
                        <?php $i++; ?>
                    <?php endforeach; ?>
                </ul>
                <?php endif;?>
            <?php endif ?>

            <?php if ( Mage::helper('neotheme_blog')->isDefaultCommentingEnabled()) : ?>
            <?php 
                $commentCount = $this->getPost()->getComments()->count();
                $commentText =  ($commentCount == 1) ? $this->__("comment"):$this->__("comments");
            ?>
            <ul>
                <li class="post-comments"><?php echo $commentCount; ?> <?php echo $commentText;?></li>
            </ul>
            <?php endif;?>
            <?php if( $this->getPost()->getProductIds()): ?>
            <section id="main">
                <div id="main-products">
                    <h3><?php echo $this->__('Produkter från den här artikeln'); ?></h3>
                    <div id="main-products-items">
                        <ul>
                            <?php $productSkus = explode(",", $this->getPost()->getProductIds());?>
                            <?php foreach ($productSkus as $productSku) : ?>
                            <?php $_product = Mage::getModel('catalog/product')->loadByAttribute('sku', $productSku);
                                if($_product):?>
                                    <li class="main-products-item">
                                        <img src="<?php echo Mage::helper('catalog/image')->init($_product, 'image')->resize(243, 354); ?>" />
                                        <div class="main-products-info">
                                    <span class="label">
                                        <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </span>
                                    <span class="price">
                                        <?php echo $formattedPrice = Mage::helper('core')->currency($_product->getFinalPrice(), true, false); ?>
                                    </span>
                                            <div class="category">
                                                <?php
                                                $catIds = $_product->getCategoryIds();
                                                $_category = Mage::getModel('catalog/category')->load($catIds[0]);
                                                echo $_category->getName();?>
                                            </div>
                                        </div>
                                    </li>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            </section>
            <?php endif; ?>
    </div>
        
        <div class="clr"></div>
    </article>
    
    <div class="comments-list">
		<?php echo $this->getChildHtml('blog.post.comment.list');?>
    </div>
    
	<div class="comment-form">
		<?php echo $this->getChildHtml('blog.post.comment.form');?>
    </div>
</div>
<?php Zend_Date::setOptions(array('format_type' => 'iso'));     ?>
